kind: PersistentVolume
apiVersion: v1
metadata:
  name: nats-js-disk
  labels:
    name: nats-js-disk
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: nats-js-disk
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nats-js-disk-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      name: nats-js-disk
